name: GTA RAGE Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { submodules: recursive }
      - uses: actions/setup-java@v4
        with: { java-version: '17', distribution: 'temurin' }
      - uses: android-actions/setup-android@v4
      - uses: nttld/setup-ndk@v1
        with: { ndk-version: r26d, link-to-sdk: true }
      - name: Get Bullet Physics
        run: git clone https://github.com/bulletphysics/bullet3 app/src/main/cpp/bullet3 --depth 1
      - uses: gradle/actions/setup-gradle@v3
        with: { gradle-version: 8.4 }
      - name: Build
        run: |
          rm -rf gradlew gradle/wrapper
          gradle assembleDebug
      - uses: actions/upload-artifact@v4
        with: { name: GTA-Morocco-RAGE-APK, path: '**/*.apk' }
